[package]
name = "zyrdeskd"
description = "Service ZyrDesk : accès distant avant ouverture de session"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
zyr-proto.workspace = true
zyr-engine-host.workspace = true
clap.workspace = true
time = { version = "0.3.55", default-features = false, features = ["std", "formatting", "macros"] }

[target.'cfg(windows)'.dependencies]
windows-service = "0.8.1"
windows-sys = { version = "0.61.2", features = [
    "Win32_Foundation",
    "Win32_Security",
    "Win32_Storage_FileSystem",
    "Win32_System_Environment",
    "Win32_System_JobObjects",
    "Win32_System_RemoteDesktop",
    "Win32_System_Threading",
] }
