[workspace]
resolver = "2"
members = [
    "crates/zyr-proto",
    "crates/zyr-engine-host",
    "crates/zyr-engine-client",
    "crates/zyr-transport",
    "crates/zyr-cli",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-only"
repository = "https://github.com/Victor-root/ZyrDesk"

[workspace.dependencies]
zyr-proto = { path = "crates/zyr-proto" }
zyr-engine-host = { path = "crates/zyr-engine-host" }
zyr-engine-client = { path = "crates/zyr-engine-client" }
zyr-transport = { path = "crates/zyr-transport" }
clap = { version = "4", features = ["derive"] }

[profile.release]
lto = "thin"
strip = "symbols"
