//! Talking to the host engine's local API.
//!
//! Two uses only: checking that the engine answers, and handing it a
//! pairing code. Everything goes through 127.0.0.1.
//!
//! The engine's certificate is self-signed and regenerated by itself, so
//! verification is turned off. That has no consequence here: the
//! connection never leaves the machine, and authentication rests on
//! random credentials that only we know.

use std::fmt;
use std::time::{Duration, Instant};

use zyr_proto::net::EnginePorts;

use crate::credentials::Credentials;

const REQUEST_TIMEOUT: Duration = Duration::from_secs(5);
const POLL_INTERVAL: Duration = Duration::from_millis(250);

#[derive(Debug)]
pub enum ApiError {
    Transport(String),
    HttpStatus(u16),
    UnreadableAnswer(String),
    PinRefused,
    TimedOut,
    /// The caller asked us to stop waiting before the delay was over.
    Abandoned,
}

impl fmt::Display for ApiError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            ApiError::Transport(e) => write!(f, "moteur injoignable : {e}"),
            ApiError::HttpStatus(code) => write!(f, "le moteur a répondu {code}"),
            ApiError::UnreadableAnswer(e) => write!(f, "réponse du moteur illisible : {e}"),
            ApiError::PinRefused => write!(f, "code d'appairage refusé par le moteur"),
            ApiError::TimedOut => write!(f, "le moteur n'a pas répondu dans le délai imparti"),
            ApiError::Abandoned => write!(f, "attente du moteur abandonnée"),
        }
    }
}

impl std::error::Error for ApiError {}

/// Address of the health probe, served in the clear on the base port.
pub fn health_url(ports: EnginePorts) -> String {
    format!("http://127.0.0.1:{}/serverinfo", ports.http())
}

/// Address of the order to stop trying to put the screens back.
pub fn stop_trying_url(ports: EnginePorts) -> String {
    format!(
        "https://127.0.0.1:{}/api/reset-display-device-persistence",
        ports.web_ui()
    )
}

/// Address of the order to film another of this computer's screens.
///
/// The engine reads which screen to film in its configuration, once,
/// when it starts. This is the other road to it, and it exists because
/// the first one costs a restart: a restart takes the tunnel with it, and
/// the tunnel takes every session going through it.
pub fn film_this_display_url(ports: EnginePorts) -> String {
    format!(
        "https://127.0.0.1:{}/api/zyr/film-this-display",
        ports.web_ui()
    )
}

/// Pairing request, built without side effects so it can be checked.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PinRequest {
    pub url: String,
    pub authorization: String,
    pub body: String,
}

/// Builds the submission of a pairing code.
///
/// The missing `Origin` header is deliberate: the engine reserves its
/// cross-site protection for browser-like clients, and the exemption
/// covers programmatic calls.
pub fn pin_request(
    ports: EnginePorts,
    credentials: &Credentials,
    pin: &str,
    device_name: &str,
) -> PinRequest {
    PinRequest {
        url: format!("https://127.0.0.1:{}/api/pin", ports.web_ui()),
        authorization: credentials.authorization_header(),
        body: serde_json::json!({ "pin": pin, "name": device_name }).to_string(),
    }
}

/// Reads the answer to a pairing code submission.
pub fn read_pin_answer(body: &str) -> Result<(), ApiError> {
    let value: serde_json::Value =
        serde_json::from_str(body).map_err(|e| ApiError::UnreadableAnswer(e.to_string()))?;
    match value.get("status").and_then(|s| s.as_bool()) {
        Some(true) => Ok(()),
        Some(false) => Err(ApiError::PinRefused),
        None => Err(ApiError::UnreadableAnswer(
            "champ « status » absent ou non booléen".to_string(),
        )),
    }
}

pub struct EngineApi {
    ports: EnginePorts,
    credentials: Credentials,
    agent: ureq::Agent,
}

impl EngineApi {
    pub fn new(ports: EnginePorts, credentials: Credentials) -> Self {
        let tls = ureq::tls::TlsConfig::builder()
            .disable_verification(true)
            .build();
        let agent = ureq::Agent::config_builder()
            .tls_config(tls)
            .timeout_global(Some(REQUEST_TIMEOUT))
            .build()
            .new_agent();
        Self {
            ports,
            credentials,
            agent,
        }
    }

    /// Ok when the engine answers its health probe.
    pub fn health(&self) -> Result<(), ApiError> {
        let answer = self
            .agent
            .get(health_url(self.ports))
            .call()
            .map_err(|e| ApiError::Transport(e.to_string()))?;
        let status = answer.status().as_u16();
        if (200..300).contains(&status) {
            Ok(())
        } else {
            Err(ApiError::HttpStatus(status))
        }
    }

    /// Waits for the engine to answer, up to the given delay.
    ///
    /// `keep_waiting` is asked between two attempts. The Windows service
    /// answers no there once it has been told to stop: a service that
    /// spends half a minute inside a start-up wait before confirming a
    /// stop is a service Windows kills, engine included.
    pub fn wait_until_ready(
        &self,
        delay: Duration,
        keep_waiting: impl Fn() -> bool,
    ) -> Result<(), ApiError> {
        let deadline = Instant::now() + delay;
        loop {
            if self.health().is_ok() {
                return Ok(());
            }
            if !keep_waiting() {
                return Err(ApiError::Abandoned);
            }
            if Instant::now() >= deadline {
                return Err(ApiError::TimedOut);
            }
            std::thread::sleep(POLL_INTERVAL);
        }
    }

    /// Tells the engine to stop trying to put the host's screens back.
    ///
    /// A last resort, and only ever after it has been given every chance
    /// to succeed. The engine remembers what the screens were before a
    /// session and keeps trying to get back to it for as long as it
    /// lives; when something else on the machine holds those screens, the
    /// two spend the evening undoing each other and the person sitting
    /// there hears it. This makes the engine forget, which is worse than
    /// a screen put back and far better than a screen that never settles.
    pub fn stop_trying_to_put_the_screens_back(&self) -> Result<(), ApiError> {
        let answer = self
            .agent
            .post(stop_trying_url(self.ports))
            .header("Authorization", &self.credentials.authorization_header())
            .send_empty()
            .map_err(|e| ApiError::Transport(e.to_string()))?;
        let status = answer.status().as_u16();
        if (200..300).contains(&status) {
            Ok(())
        } else {
            Err(ApiError::HttpStatus(status))
        }
    }

    /// Tells the engine to film that screen from now on.
    ///
    /// What it costs the engine is a reinitialization of its capture, the
    /// same one a desktop switch costs, which a session lives through.
    /// Nothing is answered about the screen itself: an engine that cannot
    /// find it waits for it and says so in its own log, exactly as it does
    /// for the screen its configuration names.
    pub fn film_this_display(&self, device_id: &str) -> Result<(), ApiError> {
        let answer = self
            .agent
            .post(film_this_display_url(self.ports))
            .header("Authorization", &self.credentials.authorization_header())
            .header("Content-Type", "application/json")
            .send(serde_json::json!({ "name": device_id }).to_string())
            .map_err(|e| ApiError::Transport(e.to_string()))?;
        let status = answer.status().as_u16();
        if (200..300).contains(&status) {
            Ok(())
        } else {
            Err(ApiError::HttpStatus(status))
        }
    }

    /// Hands a pairing code to the engine.
    pub fn submit_pin(&self, pin: &str, device_name: &str) -> Result<(), ApiError> {
        let request = pin_request(self.ports, &self.credentials, pin, device_name);
        let mut answer = self
            .agent
            .post(&request.url)
            .header("Authorization", &request.authorization)
            .header("Content-Type", "application/json")
            .send(&request.body)
            .map_err(|e| ApiError::Transport(e.to_string()))?;
        let status = answer.status().as_u16();
        if !(200..300).contains(&status) {
            return Err(ApiError::HttpStatus(status));
        }
        let body = answer
            .body_mut()
            .read_to_string()
            .map_err(|e| ApiError::UnreadableAnswer(e.to_string()))?;
        read_pin_answer(&body)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn ports() -> EnginePorts {
        EnginePorts::new(42100).unwrap()
    }

    fn credentials() -> Credentials {
        Credentials {
            user: "u".to_string(),
            password: "p".to_string(),
        }
    }

    #[test]
    fn the_health_probe_targets_the_base_port_in_the_clear() {
        assert_eq!(health_url(ports()), "http://127.0.0.1:42100/serverinfo");
    }

    #[test]
    fn the_screen_to_film_is_asked_for_on_the_engines_own_interface() {
        assert_eq!(
            film_this_display_url(ports()),
            "https://127.0.0.1:42101/api/zyr/film-this-display"
        );
    }

    #[test]
    fn the_pairing_request_targets_the_local_interface_over_https() {
        let request = pin_request(ports(), &credentials(), "1234", "LAPTOP");
        assert_eq!(request.url, "https://127.0.0.1:42101/api/pin");
        assert_eq!(request.authorization, "Basic dTpw");
    }

    #[test]
    fn the_order_to_stop_trying_targets_the_same_local_interface() {
        assert_eq!(
            stop_trying_url(ports()),
            "https://127.0.0.1:42101/api/reset-display-device-persistence"
        );
    }

    #[test]
    fn the_body_is_valid_and_escaped_json() {
        let request = pin_request(ports(), &credentials(), "0042", "PC \"quoted\"");
        let value: serde_json::Value = serde_json::from_str(&request.body).unwrap();
        assert_eq!(value["pin"], "0042");
        assert_eq!(value["name"], "PC \"quoted\"");
    }

    #[test]
    fn the_pairing_answers_are_read() {
        assert!(read_pin_answer(r#"{"status": true}"#).is_ok());
        assert!(matches!(
            read_pin_answer(r#"{"status": false}"#),
            Err(ApiError::PinRefused)
        ));
        assert!(matches!(
            read_pin_answer(r#"{"other": 1}"#),
            Err(ApiError::UnreadableAnswer(_))
        ));
        assert!(matches!(
            read_pin_answer("not json at all"),
            Err(ApiError::UnreadableAnswer(_))
        ));
    }
}
