[package]
name = "zyr-screen"
description = "Virtual screen of the host computer: installing, setting and removing the driver"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = [
    "Win32_Devices_DeviceAndDriverInstallation",
    "Win32_Devices_Display",
    "Win32_Foundation",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_Security_Cryptography",
    "Win32_System_Registry",
] }
