// FFmpeg 9.0.2: the Direct3D 11 structures of hwcontext_d3d11va.h.
//
// Generated by crates/zyr-codec/generate-bindings.sh with bindgen
// 0.73.2; run it again rather than editing this file.
// Generated for x86_64-pc-windows-gnu against the mingw-w64 d3d11.h.
// Headers: SHA-256 eb2b41db077ee9b285c2e11fa15285a39a7fb007081abefa1d161b0bc5d15ef8
// (every header of libavcodec, libavutil and libswresample, in path order).

pub type ID3D11Device = core::ffi::c_void;
pub type ID3D11DeviceContext = core::ffi::c_void;
pub type ID3D11VideoDevice = core::ffi::c_void;
pub type ID3D11VideoContext = core::ffi::c_void;
pub type ID3D11Texture2D = core::ffi::c_void;
pub type UINT = core::ffi::c_uint;

#[repr(C)]
pub struct AVD3D11VADeviceContext {
    pub device: *mut ID3D11Device,
    pub device_context: *mut ID3D11DeviceContext,
    pub video_device: *mut ID3D11VideoDevice,
    pub video_context: *mut ID3D11VideoContext,
    pub lock: ::core::option::Option<unsafe extern "C" fn(lock_ctx: *mut ::core::ffi::c_void)>,
    pub unlock: ::core::option::Option<unsafe extern "C" fn(lock_ctx: *mut ::core::ffi::c_void)>,
    pub lock_ctx: *mut ::core::ffi::c_void,
    pub BindFlags: UINT,
    pub MiscFlags: UINT,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of AVD3D11VADeviceContext"][::core::mem::size_of::<AVD3D11VADeviceContext>() - 64usize];
    ["Alignment of AVD3D11VADeviceContext"]
        [::core::mem::align_of::<AVD3D11VADeviceContext>() - 8usize];
    ["Offset of field: AVD3D11VADeviceContext::device"]
        [::core::mem::offset_of!(AVD3D11VADeviceContext, device) - 0usize];
    ["Offset of field: AVD3D11VADeviceContext::device_context"]
        [::core::mem::offset_of!(AVD3D11VADeviceContext, device_context) - 8usize];
    ["Offset of field: AVD3D11VADeviceContext::video_device"]
        [::core::mem::offset_of!(AVD3D11VADeviceContext, video_device) - 16usize];
    ["Offset of field: AVD3D11VADeviceContext::video_context"]
        [::core::mem::offset_of!(AVD3D11VADeviceContext, video_context) - 24usize];
    ["Offset of field: AVD3D11VADeviceContext::lock"]
        [::core::mem::offset_of!(AVD3D11VADeviceContext, lock) - 32usize];
    ["Offset of field: AVD3D11VADeviceContext::unlock"]
        [::core::mem::offset_of!(AVD3D11VADeviceContext, unlock) - 40usize];
    ["Offset of field: AVD3D11VADeviceContext::lock_ctx"]
        [::core::mem::offset_of!(AVD3D11VADeviceContext, lock_ctx) - 48usize];
    ["Offset of field: AVD3D11VADeviceContext::BindFlags"]
        [::core::mem::offset_of!(AVD3D11VADeviceContext, BindFlags) - 56usize];
    ["Offset of field: AVD3D11VADeviceContext::MiscFlags"]
        [::core::mem::offset_of!(AVD3D11VADeviceContext, MiscFlags) - 60usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct AVD3D11FrameDescriptor {
    pub texture: *mut ID3D11Texture2D,
    pub index: isize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of AVD3D11FrameDescriptor"][::core::mem::size_of::<AVD3D11FrameDescriptor>() - 16usize];
    ["Alignment of AVD3D11FrameDescriptor"]
        [::core::mem::align_of::<AVD3D11FrameDescriptor>() - 8usize];
    ["Offset of field: AVD3D11FrameDescriptor::texture"]
        [::core::mem::offset_of!(AVD3D11FrameDescriptor, texture) - 0usize];
    ["Offset of field: AVD3D11FrameDescriptor::index"]
        [::core::mem::offset_of!(AVD3D11FrameDescriptor, index) - 8usize];
};
#[repr(C)]
pub struct AVD3D11VAFramesContext {
    pub texture: *mut ID3D11Texture2D,
    pub BindFlags: UINT,
    pub MiscFlags: UINT,
    pub texture_infos: *mut AVD3D11FrameDescriptor,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of AVD3D11VAFramesContext"][::core::mem::size_of::<AVD3D11VAFramesContext>() - 24usize];
    ["Alignment of AVD3D11VAFramesContext"]
        [::core::mem::align_of::<AVD3D11VAFramesContext>() - 8usize];
    ["Offset of field: AVD3D11VAFramesContext::texture"]
        [::core::mem::offset_of!(AVD3D11VAFramesContext, texture) - 0usize];
    ["Offset of field: AVD3D11VAFramesContext::BindFlags"]
        [::core::mem::offset_of!(AVD3D11VAFramesContext, BindFlags) - 8usize];
    ["Offset of field: AVD3D11VAFramesContext::MiscFlags"]
        [::core::mem::offset_of!(AVD3D11VAFramesContext, MiscFlags) - 12usize];
    ["Offset of field: AVD3D11VAFramesContext::texture_infos"]
        [::core::mem::offset_of!(AVD3D11VAFramesContext, texture_infos) - 16usize];
};
