//! FFmpeg's C interface, as its headers describe it.
//!
//! Almost everything is generated by `generate-bindings.sh`, and the
//! lints allowed below are about what it copies from C as it is:
//! FFmpeg's own names, which match the documentation they come from,
//! its function shapes, and whole types (every value of an enumeration,
//! every field of a structure), not all of which are read here.
//!
//! What is written by hand is the pair of logging functions: they take
//! a `va_list`, which bindgen spells differently on each system.

use core::ffi::{c_char, c_int, c_void};

#[allow(
    dead_code,
    non_camel_case_types,
    non_snake_case,
    non_upper_case_globals,
    clippy::too_many_arguments,
    clippy::type_complexity
)]
mod bindings;

pub use bindings::*;

/// What FFmpeg calls for every line it logs.
///
/// The last argument is a `va_list`. The two ABIs the engine runs on
/// pass one as a pointer (Windows x64 makes it one, System V x86-64
/// hands over a pointer to its array), so it travels here as an opaque
/// pointer and goes back untouched to `av_log_format_line2`.
pub type LogCallback = unsafe extern "C" fn(
    context: *mut c_void,
    level: c_int,
    format: *const c_char,
    args: *mut c_void,
);

/// `av_log_set_callback`.
pub type SetLogCallback = unsafe extern "C" fn(callback: Option<LogCallback>);

/// `av_log_format_line2`, which writes one line the way FFmpeg's own
/// callback would, its `va_list` taken the same way as above.
pub type FormatLogLine = unsafe extern "C" fn(
    context: *mut c_void,
    level: c_int,
    format: *const c_char,
    args: *mut c_void,
    line: *mut c_char,
    line_size: c_int,
    print_prefix: *mut c_int,
) -> c_int;

/// The two logging functions of avutil.
pub struct Logging {
    pub set_callback: SetLogCallback,
    pub format_line: FormatLogLine,
}

impl Logging {
    /// The names resolved, for the loader to check first.
    pub const FUNCTIONS: &[&str] = &["av_log_set_callback", "av_log_format_line2"];

    /// Resolves both functions in avutil.
    ///
    /// # Safety
    ///
    /// `library` must be FFmpeg's avutil, whose functions have the
    /// signatures above (libavutil/log.h), and must stay loaded for as
    /// long as the result is used.
    pub unsafe fn from_library(library: &libloading::Library) -> Result<Self, libloading::Error> {
        // SAFETY: the caller vouches for the library; the types match
        // the declarations of log.h, with the va_list as a pointer.
        unsafe {
            Ok(Self {
                set_callback: *library.get(c"av_log_set_callback")?,
                format_line: *library.get(c"av_log_format_line2")?,
            })
        }
    }
}
