//! Video and audio codecs of the ZyrDesk engine.
//!
//! FFmpeg 9.0.2 does the encoding and decoding: it speaks to the
//! hardware encoders of the three graphics card makers and to the
//! hardware decoders through Direct3D 11, and has x264 and Opus built
//! in. It is not linked when the engine is built but opened when it
//! runs, from `vendor/ffmpeg` (see [`Ffmpeg::load`]): building ZyrDesk
//! asks for nothing more than Rust.
//!
//! Every FFmpeg object is owned by a Rust value that frees it, every
//! failure carries FFmpeg's own words, and nothing FFmpeg allocated is
//! ever handed out: packets and sound are copied out, pictures stay
//! wrapped.
//!
//! The bindings in `src/sys` are generated by `generate-bindings.sh`,
//! which says how and when to run it again.
//!
//! # Tests
//!
//! The tests run FFmpeg for real, so they need a build of it for the
//! system they run on. They load it from the folder named by the
//! `ZYR_FFMPEG_DIR` environment variable, and else from `vendor/ffmpeg`,
//! which only holds the Windows build. On Linux:
//!
//! ```text
//! packaging/ffmpeg/build.sh linux /some/where
//! ZYR_FFMPEG_DIR=/some/where/lib cargo test -p zyr-codec
//! ```
//!
//! Without it, the tests that need FFmpeg fail and say so; they never
//! pass without having run.

#[cfg(windows)]
mod d3d11;
mod decoder;
mod encoder;
mod error;
mod library;
mod log;
mod opus;
mod owned;
mod probe;
mod resample;
mod sys;
#[cfg(test)]
mod testing;
mod tuning;

#[cfg(windows)]
pub use d3d11::{D3d11Picture, GpuFrame, Sampling};
pub use decoder::{CpuPicture, DecodeOutput, DecodedFrame, PictureLayout, Plane, VideoDecoder};
pub use encoder::{
    Applied, Backend, CpuFrame, EncodedPacket, EncoderConfig, Frame, Input, Nv12Planes,
    VideoEncoder,
};
pub use error::CodecError;
pub use library::Ffmpeg;
pub use opus::{OPUS_FRAME, OpusDecoder, OpusEncoder};
pub use probe::{GpuVendor, probe};
pub use resample::{AudioFormat, Resampler};
